
project_id = "hfnnbcvqhdbwylxmcwjb"

[api]
# No custom API config

[db]
# No custom database config

[realtime]
# No custom realtime config

[storage]
# No custom storage config

[auth]
# No custom auth config

[functions.guest-auth]
verify_jwt = false

[functions.migrate-guest-data]
verify_jwt = true
