// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfnnbcvqhdbwylxmcwjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhmbm5iY3ZxaGRid3lseG1jd2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTg5MDgsImV4cCI6MjA2MTc3NDkwOH0.mebcZT9GitHB8s2RpXaSKeaFHBePmOef-QMcryRGqkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);